import type { CryptoAsset, OpeningScenarioSettings } from "./types.js";

export const BLACK_GOAT_V3_CONFIG = {
  version: "black-goat-v3-final-settlement-opening-scenario-smart-scaling",
  mode: {
    allowRealOrders: false,
    liveTradingEnabled: false,
    paperTradingOnly: true,
    readOnlyPolymarket: true,
  },
  marketScanner: {
    allowedAssets: ["BTC", "ETH", "SOL", "XRP", "DOGE", "BNB", "HYPE"] as CryptoAsset[],
    analyzeEvery5mMarket: true,
    enabled: true,
    ignoreMarketIfExpiryMissing: true,
    ignoreMarketIfTargetMissing: true,
    marketDurationMinutes: 5,
    requireParsedSettlementRule: true,
    requireParsedTargetPrice: true,
    scanEverySeconds: 5,
  },
  mandatoryMarketDecision: {
    enabled: true,
    forcePickEvenIfNoTrade: true,
    logBlockedDecisions: true,
    mustProduceDecision: true,
    mustProduceForcedPaperPick: true,
    openRealPaperPositionOnlyIfApproved: true,
  },
  finalSettlementEngine: {
    allowNoWhenCurrentPriceAboveTarget: true,
    allowYesWhenCurrentPriceBelowTarget: true,
    contrarianMinConfidence: 0.62,
    contrarianMinEdgeNet: 0.1,
    enabled: true,
    minForecastConfidenceForAdd: 0.62,
    minForecastConfidenceForStarter: 0.56,
    minForecastConfidenceForStrongEntry: 0.64,
    nearTargetBps: 4,
    nearTargetRequiresMomentumConfirmation: true,
    requireContrarianConfirmation: true,
    timeframes: ["1M", "1W", "1D", "4H", "1H", "15m", "5m", "3m", "1m"],
    useMultiTimeframeAnalysis: true,
    weights: {
      "1M": 0.04,
      "1W": 0.07,
      "1D": 0.12,
      "4H": 0.14,
      "1H": 0.18,
      "15m": 0.18,
      "5m": 0.16,
      "3m": 0.09,
      "1m": 0.08,
    },
    features: {
      useAtr: true,
      useBreakoutDetection: true,
      useDistanceToTarget: true,
      useEmaTrend: true,
      useMacd: true,
      useMarketStructure: true,
      useMomentumTowardTarget: true,
      useRejectionDetection: true,
      useRsi: true,
      useTimeRemaining: true,
      useVolumeSpike: true,
      useVwap: true,
    },
  },
  entryOpportunityEngine: {
    confirmationEntryMaxAsk: 0.62,
    lowLiquidityPenalty: 0.03,
    maxAcceptableAskPrice: { NO: 0.72, YES: 0.72 },
    minEdgeNetForAdd: 0.07,
    minEdgeNetForStarter: 0.05,
    minEdgeNetForStrongStarter: 0.1,
    preferLowPriceEntry: true,
    safetyMargin: 0.03,
    spreadPenaltyMultiplier: 1.25,
    uncertaintyPenalty: 0.03,
    valueEntryMaxAsk: 0.45,
    entryModes: {
      aboveConfirmationEntry: { enabled: true, maxYesAsk: 0.62, minEdgeNet: 0.05, minProbabilityFinalAbove: 0.62 },
      aboveValueEntry: { enabled: true, maxYesAsk: 0.45, minEdgeNet: 0.08, minProbabilityFinalAbove: 0.56 },
      belowConfirmationEntry: { enabled: true, maxNoAsk: 0.62, minEdgeNet: 0.05, minProbabilityFinalBelow: 0.62 },
      belowValueEntry: { enabled: true, maxNoAsk: 0.45, minEdgeNet: 0.08, minProbabilityFinalBelow: 0.56 },
    },
  },
  starterEntry: {
    blockIfForecastUnclear: true,
    blockIfLiquidityScoreBelow: 60,
    blockIfSpreadAbovePercent: 4,
    enabled: true,
    entryAtMarketOpenAllowed: true,
    maxStarterStakeUsd: 1,
    maxTimeRemainingSeconds: 295,
    minStakeUsd: 1,
    minTimeRemainingSeconds: 210,
    sizeBySignal: {
      normal: 0.35,
      strong: 0.5,
      weak: 0.25,
    },
    starterSizeMode: "confidence_scaled",
  },
  openingScenarioBot: {
    allowedAssets: ["BTC", "ETH", "SOL", "XRP", "DOGE", "BNB", "HYPE"] as CryptoAsset[],
    analyzeEveryMarketOpen: true,
    doNotForceUnclearBecauseNearTargetAtOpen: true,
    enabled: true,
    mustChoosePrimaryScenario: true,
    mustCreateForcedPaperPick: true,
    mustCreateThreeScenarios: true,
    nearTargetAtOpenIsAllowed: true,
    paperTradingOnly: true,
    preOpenAnalysis: {
      enabled: true,
      lookbackSeconds: 300,
      use15mCandles: true,
      use1hContext: true,
      use1mCandles: true,
      use3mCandles: true,
      use4hContext: true,
      use5mCandles: true,
      usePreviousMarketLastMinutes: true,
    },
    profileName: "Opening Scenario Bot",
    readOnlyPolymarket: true,
    usePreOpenBiasWhenNearTarget: true,
    scenarioSelection: {
      minEdgeNetForPrimaryScenario: 0.04,
      minPrimaryScenarioConfidence: 0.54,
      minPrimaryScenarioProbability: 0.53,
      minProbabilityGapToAvoidUnclear: 0.06,
      preferNoTradeWhenScenarioGapSmall: true,
    },
    openingEntry: {
      allowOpeningEntryIfForecastUnclear: false,
      allowOpeningEntryIfLiquidityLow: false,
      allowOpeningEntryIfSpreadWide: false,
      availableEntryModes: ["OFF", "IF_APPROVED", "FORCED_PAPER_ONLY", "FORCED_MIN_STAKE_PAPER"],
      enabled: true,
      entryDelayMs: 750,
      entryMode: "FORCED_MIN_STAKE_PAPER",
      entryWindowSeconds: 12,
      maxOpeningStakeUsd: 1,
      minConfidenceForOpeningEntry: 0.54,
      minEdgeNetForOpeningEntry: 0.04,
      minStakeUsd: 1,
      openAtMarketStart: true,
      requireEdgeForOpeningEntry: true,
    },
    openingRisk: {
      blockIfDataStale: true,
      blockIfLiquidityScoreBelow: 60,
      blockIfSpreadAbovePercent: 4,
      maxOpeningPositions: 3,
      maxOpeningPositionsSameAsset: 1,
      maxOpeningPositionsSameDirection: 2,
    },
    smartScalingAfterOpening: {
      blockAddIfForecastUnclear: true,
      blockAddIfPrimaryScenarioChanges: true,
      enabled: true,
      maxAddsAfterOpening: 2,
      useExistingSmartScalingEngine: true,
    },
    strategyVersion: "v3-opening-scenario-final-settlement",
    threeScenarioEngine: {
      includeExpectedPath: true,
      includeInvalidationCondition: true,
      includeMaxAcceptableAskPrice: true,
      includeReasonCodes: true,
      scenarioA: "ABOVE_TARGET",
      scenarioB: "BELOW_TARGET",
      scenarioC: "UNCLEAR_CHOP",
    },
    userEditable: true,
  },
  smartScalingEngine: {
    allowConfirmationAdd: true,
    allowValueAdd: true,
    confirmationAdd: {
      addSizeMultiplier: 0.6,
      blockIfTokenAskAbove: 0.72,
      enabled: true,
      minEdgeNetForHigherAdd: 0.08,
      minProbabilityIncrease: 0.08,
      requireSameForecast: true,
    },
    hardBlocks: {
      blockAddIfEdgeNetBelow: 0.03,
      blockAddIfForecastOpposite: true,
      blockAddIfForecastUnclear: true,
      blockAddIfLiquidityScoreBelow: 60,
      blockAddIfMaxPositionReached: true,
      blockAddIfSpreadAbovePercent: 4,
      blockAddIfTimeRemainingBelowSeconds: 60,
    },
    maxAddsPerMarket: 2,
    maxPositionPerMarketUsd: 2,
    minSecondsBetweenAdds: 20,
    valueAdd: {
      addSizeMultiplier: 1,
      enabled: true,
      maxProbabilityDropAllowed: 0.03,
      minEdgeNetForAdd: 0.07,
      requireSameForecast: true,
      requireScenarioStillValid: true,
    },
  },
  deRiskEngine: {
    exitIfEdgeNetBelow: 0,
    exitIfForecastOpposite: true,
    exitIfForecastUnclearAndEdgeGone: true,
    exitIfProbabilityBelow: 0.5,
    partialProfitPercent: 0.5,
    protectProfitIfTimeRemainingBelowSeconds: 45,
    takePartialProfitEnabled: true,
    takePartialProfitIfTokenPriceAbove: 0.75,
  },
  marketQuality: {
    maxSpreadPercent: 4,
    maxSpreadPercentStrongSignal: 5,
    maxAllowedSlippagePercent: 1.5,
    minFillProbability: 0.75,
    minLiquidityScore: 60,
    useOrderbookBasedSlippage: true,
  },
  dataFreshness: {
    blockIfCriticalDataStale: true,
    maxCryptoPriceAgeMs: 1_000,
    maxForecastAgeMs: 2_000,
    maxPolymarketBookAgeMs: 1_500,
  },
  dashboard: {
    showBlockedReason: true,
    showCurrentPrice: true,
    showDistanceToTarget: true,
    showEdgeYesEdgeNo: true,
    showEntryMode: true,
    showFinalSettlementPanel: true,
    showForcedPaperPick: true,
    showOpeningScenarioBot: true,
    showProbabilityFinalAbove: true,
    showProbabilityFinalBelow: true,
    showScalingState: true,
    showTargetLine: true,
    showYesAskNoAsk: true,
  },
  exports: {
    includeDeRiskDiagnostics: true,
    includeFinalSettlementFields: true,
    includeForcedPaperPick: true,
    includeOpeningScenarioFields: true,
    includeSmartScalingDiagnostics: true,
  },
} as const;

export const DEFAULT_OPENING_SCENARIO_SETTINGS: OpeningScenarioSettings = {
  allowedAssets: [...BLACK_GOAT_V3_CONFIG.openingScenarioBot.allowedAssets],
  doNotForceUnclearBecauseNearTargetAtOpen: BLACK_GOAT_V3_CONFIG.openingScenarioBot.doNotForceUnclearBecauseNearTargetAtOpen,
  enabled: BLACK_GOAT_V3_CONFIG.openingScenarioBot.enabled,
  entryDelayMs: BLACK_GOAT_V3_CONFIG.openingScenarioBot.openingEntry.entryDelayMs,
  entryMode: BLACK_GOAT_V3_CONFIG.openingScenarioBot.openingEntry.entryMode,
  entryWindowSeconds: BLACK_GOAT_V3_CONFIG.openingScenarioBot.openingEntry.entryWindowSeconds,
  maxOpeningStakeUsd: BLACK_GOAT_V3_CONFIG.openingScenarioBot.openingEntry.maxOpeningStakeUsd,
  maxSpreadPercent: BLACK_GOAT_V3_CONFIG.openingScenarioBot.openingRisk.blockIfSpreadAbovePercent,
  minConfidenceForOpeningEntry: BLACK_GOAT_V3_CONFIG.openingScenarioBot.openingEntry.minConfidenceForOpeningEntry,
  minEdgeNetForOpeningEntry: BLACK_GOAT_V3_CONFIG.openingScenarioBot.openingEntry.minEdgeNetForOpeningEntry,
  minLiquidityScore: BLACK_GOAT_V3_CONFIG.openingScenarioBot.openingRisk.blockIfLiquidityScoreBelow,
  minStakeUsd: BLACK_GOAT_V3_CONFIG.openingScenarioBot.openingEntry.minStakeUsd,
  nearTargetAtOpenIsAllowed: BLACK_GOAT_V3_CONFIG.openingScenarioBot.nearTargetAtOpenIsAllowed,
  openAtMarketStart: BLACK_GOAT_V3_CONFIG.openingScenarioBot.openingEntry.openAtMarketStart,
  smartScalingAfterOpening: BLACK_GOAT_V3_CONFIG.openingScenarioBot.smartScalingAfterOpening.enabled,
  usePreOpenBiasWhenNearTarget: BLACK_GOAT_V3_CONFIG.openingScenarioBot.usePreOpenBiasWhenNearTarget,
};
